# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby_prototype}
  s.version = "1.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack Danger Canty"]
  s.date = %q{2011-04-10}
  s.description = %q{Allows the class-oriented Ruby language to double as a simple-object prototype language (a la Javascript)}
  s.email = %q{gems@6brand.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".gemtest",
    "History.txt",
    "LICENSE",
    "Manifest.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/ruby_prototype.rb",
    "lightning.html",
    "lightning.rb",
    "ruby_prototype.gemspec",
    "test/ruby_prototype_test.rb"
  ]
  s.homepage = %q{http://github.com/JackDanger/ruby_prototype}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Provides Ruby1.9 with a method prototyping interface}
  s.test_files = [
    "test/ruby_prototype_test.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

